
##############################################
# Odatix settings for fmax synthesis
##############################################
---

# overwrite existing results
overwrite:        No

# prompt 'Continue? (Y/n)' after settings checks
ask_continue:     Yes

# exit monitor when all jobs are done
exit_when_done:   Yes

# size of the log history per job in the monitor
log_size_limit:   300

# maximum number of parallel synthesis
nb_jobs:          8

# targeted architectures
architectures: 

#--------------------------------------------#
# Add your own designs!
#--------------------------------------------#

  #- Your_Design/Your_1st_Configuration
  #- Your_Design/Your_2nd_Configuration
  #- Your_Design/Your_3rd_Configuration

...
