
##############################################
# Settings for counter testbench
##############################################
---

# delimiters for parameter files
use_parameters: Yes
param_target_file: "tb/tb_counter.vhdl"
start_delimiter: "generic ("
stop_delimiter: ");"

# override part of the parameters
override_parameters: No